services:
  microsandbox:
    image: microsandbox:${BUILD_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5555:5555"
    volumes:
      - /dev/shm:/dev/shm
      - /dev/kvm:/dev/kvm
      - ./data:/root/.microsandbox
